name: 'action-remote-github-app-token'
description: 'Gets a Remote GitHub auth token for an installed on a GitHub App installation installed on a remote Github server'
author: 'Moe Moghaddam'
inputs:
  remoteGithubApiUrl:
    required: true
    description: 'The Remote Github API URL, e.g., for Github this is: https://api.github.com'
  app_id:
    required: true
    description: 'GitHub App ID'
  private_key:
    required: true
    description: 'Private key for the GitHub App'
  scope:
    required: false
    description: 'Scope of installation account'
    default: ''
outputs:
  token:
    description: 'Remote Github Token for App installation'
runs:
  using: 'node12'
  main: 'dist/index.js'
